### ISSUE TITLE
`mkPackageOption` helper with `defaultText`

### ISSUE THREAD

**Issue by MattSturgeon** [nix-community/nixvim#1950]
Nixpkgs has `lib.mkPackageOption` ([documentation](https://nixos.org/manual/nixos/unstable/#sec-option-declarations-util-mkPackageOption), [noogle](https://noogle.dev/f/lib/options/mkPackageOption), [source](https://github.com/NixOS/nixpkgs/blob/e1d5bdcc6c01d7a764b0239cbdf20dcceaac393d/lib/options.nix#L107-L221)) which takes a "pkgs path" and produces an option with an appropriate default and literalExpression defaultText.

```nix
# e.g.
lib.mkPackageOption pkgs "hello" { }
# is like
lib.mkOption {
  type = lib.types.package;
  default = pkgs.hello;
  defaultText = lib.literalExpression "pkgs.hello";
  description = "The hello package to use.";
}
```

We should use this where possible, and copy the implementation in our nullable version.

We could do this in a non-breaking way by having our nullable helper check the `pkg` arg type; lists and strings can be pkgs-paths while derivations should be actual packages.

Eventually, we could warn when a derivation is passed in to hunt down any remaining call sites, but I see this more as something that can improve future code rather than something we should be in a hurry to migrate existing code to.

# TODO:
- [x] Add support to `mkVimPlugin` and `mkNeovimPlugin`
      #2139
- [x] Implement fancier support (i.e. adding the option _within_ `mkNeovimPlugin`, using an imported module)
- [x] Migrate all plugins `defaultPackage`
- [x] Remove the deprecated helpers (`mkPackageOption` & `mkPluginPackageOption`)

**Comment by MattSturgeon** [comment]
We have two helpers currently.

- `mkPluginPackageOption`, is also just `types.package`.
  - Used 93 times accross the codebase
  - Two of those are in `mkNeovimPlugin` and `mkVimPlugin`...
  - This function could be replaced with nixpkg's `mkPackageOption`, or could be a wrapper that sets a custom description.
- `mkPackageOption` is similar, but has a `nullOr` type.
  - It is currently used 51 times across the codebase.

**Comment by MattSturgeon** [comment]
Fixed by #2150
