### ISSUE TITLE
[TRACKING] Lazy loading roadmap

### ISSUE THREAD

**Issue by GaetanLepage** [nix-community/nixvim#2632]
# Lazy loading roadmap

As #2602 was merged and #421 closed, we will use this new issue to track the remaining steps for a broader lazy loading (LL) support.

- [ ] Add top-level documentation (https://github.com/nix-community/nixvim/pull/2630)
- [ ] Advertise the feature on the README
- [ ] Migrate all relevant packages to `mkNeovimPlugin` to have more plugins supporting LL.
- [ ] Remove "experimental" warnings (once stability is confirmed)
- [ ] Support the [lazy.nvim](https://github.com/folke/lazy.nvim) backend (https://github.com/nix-community/nixvim/pull/2620)
- [ ] Enable lazy loading by default on supported plugins ?
  -> Not sure about this one. Again, Nixvim is not a distribution. It should not do much OOTB (i.e. behind your back).

Feel free to propose additional goals !

Thanks @trueNAHO for the idea

**Comment by Eveeifyeve** [comment]
I feel like it should be default because it would be a pain to enable lazyloading for every single plugin. 
An example, before lazyloading you have 50-100+ plugins that you have enabled and want lazy loading on all of them, it would be a pain to go ahead and enable lazyloading for all of them.

I feel like there should be a seprate option to enable lazyloading for all plugins by default on but users can turn it off if it's annoying. So an example of this could be:

```nix
programs.nixvim.plugins = {
   lazyloading = true; # false if you want to only select specific plugins
   
   # with the main lazyloading
   noice-nvim.enable = true;
   
   # Manually specifying plugins that you want lazyloading on
   noice-nvim = {
    enable = true;
    lazyloading = false; # This should still work if lazyloading is enabled in plugins as well as specifically affecting that plugin.
  }
};
```
I get this might sound complicated, but it could solve the lazy loading by default on plugins problem.

**Comment by MattSturgeon** [comment]
> I feel like it should be default because it would be a pain to enable lazyloading for every single plugin.

I'm going to assume you mean the per-plugin `plugins.*.lazyload.enable` option should default to `true`. Having lazyloading itself globally enabled by default is not something nixvim will do, because everything in a nixvim config should come from the end-user explicitly deciding to do something.

The issue with having `plugins.*.lazyload.enable` default to `true`, is deciding _what_ triggers individual plugins to be loaded. That is why it currently defaults to "whether `plugins.*.lazyload.settings` contains a non-null attr"[^1].

See the [documentation](https://nix-community.github.io/nixvim/plugins/aerial/lazyLoad.html) for more detail.

If it is set to true without any sensible config in `plugins.*.lazyload.settings`, then the plugin will simply never load. For lazy loading to make sense, you need to decide which keybinds, filetypes, autocmd events, etc should trigger loading.

[^1]: `default = lib.any (x: x != null) (builtins.attrValues config.settings)`

**Comment by Eveeifyeve** [comment]
> > I feel like it should be default because it would be a pain to enable lazyloading for every single plugin.
> 
> I'm going to assume you mean the per-plugin `plugins.*.lazyload.enable` option should default to `true`.
No, Just please have a look at the example provided below.

**Comment by MattSturgeon** [comment]
> > I'm going to assume you mean the per-plugin `plugins.*.lazyload.enable` option should default to `true`.
> 
> No, Just please have a look at the example provided below.

I'm sorry, the example doesn't make sense because nowhere is it specified _when_ the plugin should be loaded.

See the rest of my comment above, but as a TL;DR: lazyloading requires you to decide what "event(s)" should cause the plugin to load.

---

Also, as a side-note: your example doesn't match how we currently have the options structured:
- You're using `plugins.*.lazyload` as a boolean, but it is actually an attrset containing an `enable` and `settings` options.
- You have a "global" `plugins.lazyload` option, however we expect this to be configured as `plugins.lz-n.enable`.

**Comment by Eveeifyeve** [comment]
I will look into make a POC pr and it will hopefully make sense.

**Comment by HeitorAugustoLN** [comment]
I don't making lazy-loading enabled by default is good. Not all plugins should be lazy-loaded, in fact, many plugins can break if you lazy-load them. Plus, not everyone even likes lazy-loading, for them, lazy-loading by default would just feel like an unnecessary hassle.

Another issue is figuring out when plugins should load. If the triggers (like keybindings or filetypes) aren’t set up right, some plugins might never load at all. That’s a confusing problem to deal with, especially for new users.

I think the current way of enabling lazy-loading, only if the user passes specific configuration, is the right way. It ensures lazy-loading is only applied when the user explicitly sets it up

**Comment by Eveeifyeve** [comment]
> I don't making lazy-loading enabled by default is good. Not all plugins should be lazy-loaded, in fact, many plugins can break if you lazy-load them. Plus, not everyone even likes lazy-loading, for them, lazy-loading by default would just feel like an unnecessary hassle.
> Another issue is figuring out when plugins should load. If the triggers (like keybindings or filetypes) aren’t set up right, some plugins might never load at all. That’s a confusing problem to deal with, especially for new users.

I agree with this. I think it shouldn't but there should be a global way and when you use the lazyloading option in the plugin it overrides the global like I said above.

> I think the current way of enabling lazy-loading, only if the user passes specific configuration, is the right way. It ensures lazy-loading is only applied when the user explicitly sets it up

I still think there could be a couple improvements like adding a global option to enable it for all plugins and make it to so if you modify the plugin option it overrides what the global option does. I will make a pr of it soon!

**Comment by HeitorAugustoLN** [comment]
> I agree with this, I think it shouldn't be default after just now thinking, but there should be a global way and when you use the lazyloading option in the plugin it overrides the global like I said above.

I don’t think having a global lazy-loading option is a good idea either. The main problem is that you’d need to set up the lazy-loading triggers in a way that works for most plugins, which is nearly impossible. Plugins usually need specific configurations to determine when they should load, like on a command, a keymap, an event, or something else.

And if you try to apply the same global lazy-loading configuration to all plugins, they’d all end up with the same trigger unless overridden. And at that point, you’re back to square one, either not actually lazy-loading most plugins or needing to override so many of them that the global option becomes pointless.

Lazy-loading really needs to be done plugin by plugin to make sense. It’s better to stick with the current approach where the user explicitly sets it up when and how it’s needed.

**Comment by Eveeifyeve** [comment]
> > I agree with this, I think it shouldn't be default after just now thinking, but there should be a global way and when you use the lazyloading option in the plugin it overrides the global like I said above.
> 
> I don’t think having a global lazy-loading option is a good idea either. The main problem is that you’d need to set up the lazy-loading triggers in a way that works for most plugins, which is nearly impossible. Plugins usually need specific configurations to determine when they should load, like on a command, a keymap, an event, or something else.
> 
> And if you try to apply the same global lazy-loading configuration to all plugins, they’d all end up with the same trigger unless overridden. And at that point, you’re back to square one, either not actually lazy-loading most plugins or needing to override so many of them that the global option becomes pointless.
> 
> Lazy-loading really needs to be done plugin by plugin to make sense. It’s better to stick with the current approach where the user explicitly sets it up when and how it’s needed.

I get that but that's why I mentioned there is a possibility of overriding it but just to enable lazy loading. Not settings as settings for how it will be loaded I just want a globalEnable option so you don't have to do for every single plugin `plugins.*.lazyloading.enable = true;`

**Comment by HeitorAugustoLN** [comment]
> I get that but that's why I mentioned there is a possibility of overriding it but just to enable lazy loading. Not settings as settings for how it will be loaded I just want a globalEnable option so you don't have to do for every single plugin `plugins.*.lazyloading.enable = true;`

You don’t need to set `plugins.*.lazyLoad.enable` explicitly for every plugin. The way it works now, lazy-loading is automatically enabled as long as you pass the lazy-loading settings. For example, you can just set something like:

```nix
plugins.which-key.lazyLoad.settings.event = "VimEnter";
```

**Comment by Eveeifyeve** [comment]
> > I get that but that's why I mentioned there is a possibility of overriding it but just to enable lazy loading. Not settings as settings for how it will be loaded I just want a globalEnable option so you don't have to do for every single plugin `plugins.*.lazyloading.enable = true;`
> 
> You don’t need to set `plugins.*.lazyLoad.enable` explicitly for every plugin. The way it works now, lazy-loading is automatically enabled as long as you pass the lazy-loading settings. For example, you can just set something like:
> 
> ```nix
> plugins.which-key.lazyLoad.settings.event = "VimEnter";
> ```

But still I don't want to have to do that for every plugin that I want lazily loaded.

**Comment by MattSturgeon** [comment]
> > The way it works now, lazy-loading is automatically enabled as long as you pass the lazy-loading settings. For example, you can just set something like:
> > ```nix
> >  plugins.which-key.lazyLoad.settings.event = "VimEnter";
> >  ```
>
> But still I don't want to have to do that for every plugin that I want lazily loaded.

I don't see a sensible alternative.

If you want a plugin lazy loaded, you should have some idea of why you want it lazy loaded; i.e. when you need it loaded and when you don't.

Therefore you need to decide for yourself what events will cause that plugin to load.

If you don't do that, we can't really guess for you. Because while _you_ might want to load on `VimEnter`, someone else might want to load on something entirely different. Or they may want the plugin eagerly loaded.

---

In theory, nixvim could maintain bespoke sane defaults for every plugin. However this is impractical because we have way too many plugins and we don't want to increase our already high per-plugin maintenance cost.

Even if nixvim did maintain per-plugin defaults, it still seems likely that many users would disagree with our choices. It'd actually be more work for them to "undo" our choices instead of starting from a blank slate.

**Comment by Mikilio** [comment]
I think it might be cool to use a sensible default equivalent to what is advertised on the plugins GitHub page, though that seems like a lot of manual maintenance, which at least I would not want to do.

**Comment by Eveeifyeve** [comment]
>[ ]  Enable lazy loading by default on supported plugins ?
>   -> Not sure about this one. Again, Nixvim is not a distribution. It should not do much OOTB (i.e. behind your back).

I feel like this should be a seperate option to say yes to define Lazyload event automatically, but leave the other options for your self to be defined. Yes it would be a lot of maintenance since there will be loads of lazyloads in the code but it would be much cleaner code for the end user and not for example spending time looking up plugin, finding the lazy event adding it to the plugin code then repeating that for 100 plugins for example when converting everything to lazy loaded.

**Comment by Mikilio** [comment]
Not gonna lie: that was the exact experience that I had 😂
But there are many times where you would need a human brain to figure out what the correct triggers are. (I tried AI first)

So while it's tedious it's not exactly trivial and "easy" to automate.

**Comment by GaetanLepage** [comment]
Thanks for the feedback. I would personally advocate against this feature.
As you said, this would involve extra maintenance work on which we currently cannot commit to spending the bandwidth.
Therefore, I would rather leave it to the users to configure lazy loading events than to ship potentially broken/outdated configs.

**Comment by HeitorAugustoLN** [comment]
There's also no alternative for default lazy-loading triggers outside Nixvim, so it doesn't even make sense to implement it, specially, since Nixvim is not a Neovim distribution

**Comment by Mikilio** [comment]
May be can link some example configs in the docs for lazy loading?

**Comment by musjj** [comment]
Someone really needs to update the readme tbh:

> ## What is it?
> NixVim is a **[Neovim](https://neovim.io/) distribution** built around [Nix](https://nixos.org/) modules

**Comment by Eveeifyeve** [comment]
> Someone really needs to update the readme tbh:
> 
> > ## What is it?
> > NixVim is a **[Neovim](https://neovim.io/) distribution** built around [Nix](https://nixos.org/) modules

Not this again https://github.com/NixOS/nixpkgs/issues/387072 but enforcing in prs.

**Comment by MattSturgeon** [comment]
_Technically_ nixvim is a neovim distribution.

The distinction is more that we don't aim to be a "batteries included" distro that configures a bunch of stuff _for_ the user and/or writes a whole bunch of lua out of the box. Which is usually what is meant by neovim distribution (colloquially).

Rather, we try to be a configuration framework that describes neovim APIs and plugin settings using nix's module system.

I agree that we should improve the README though, and rephrase that summary. PRs always welcome 😉

**Comment by ForsakenHarmony** [comment]
Can this issue get pinned instead of the old closed one?
Maybe the `mkNeovimPlugin` tracking issue as well

**Comment by saygo-png** [comment]
I think lazyload support for `mkVimPlugin` should be added as a goal. https://github.com/nix-community/nixvim/issues/3313

**Comment by eveeifyeve** [comment]
>       -> Not sure about this one. Again, Nixvim is not a distribution. It should not do much OOTB (i.e. behind your back).

I have created a repo today and about to get work on this unofficially: https://github.com/digitalbrewstudios/lazy-nixvim
